### ISSUE TITLE
uwaterloo enrollSubmitButton id

### ISSUE THREAD

**Issue by lelandjansen** [nlieb/university-enroll#6]
In `config.json` uwaterloo's `enrollSubmitButton` id is `DERIVED_REGFRM1_LINK_ADD_ENRL` whereas ualbera's id is `DERIVED_REGFRM1_LINK_ADD_ENRL$291$` (with `$291$` appended). **Just wanted to make sure this correct?** From my experience with BearTracks' HTML this will not match anything.

Abridged BearTracks HTML for the enroll button:
```
<div id="win0divDERIVED_REGFRM1_LINK_ADD_ENRL$291$">
<span id="DERIVED_REGFRM1_LINK_ADD_ENRL$291$$span" ...>
<a ... id="DERIVED_REGFRM1_LINK_ADD_ENRL$291$" ...>
```

If this is not the desired behavior I'll get together a PR.

**Comment by lelandjansen** [comment]
@nwestbury Would you be willing to confirm this?

**Comment by nwestbury** [comment]
Can confirm this is correct, there is no $291$ added to uwaterloo's page. A little bizarre difference for sure.
